// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5PKh73RMbZ0UGRbd9pcr0NBtbxLT4eHM',
    appId: '1:733722860103:web:c3d8d7cf396c76bae32f62',
    messagingSenderId: '733722860103',
    projectId: 'shelfd-41c13',
    authDomain: 'shelfd-41c13.firebaseapp.com',
    storageBucket: 'shelfd-41c13.firebasestorage.app',
    measurementId: 'G-73DX0SJ9V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaKanlTkvCmZwvZPWxUlQWq-xBu7vvlTg',
    appId: '1:733722860103:android:26c44e560e924d0ee32f62',
    messagingSenderId: '733722860103',
    projectId: 'shelfd-41c13',
    storageBucket: 'shelfd-41c13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-AREfBoXwWnFtI4xGLtNzu4Moz_fixUk',
    appId: '1:733722860103:ios:46dda18fc8a002e4e32f62',
    messagingSenderId: '733722860103',
    projectId: 'shelfd-41c13',
    storageBucket: 'shelfd-41c13.firebasestorage.app',
    androidClientId: '733722860103-fj6plrhnufpdli34lm7qf1dgsdknvqc8.apps.googleusercontent.com',
    iosClientId: '733722860103-83htvqj5epf8vakv70rcq0bsek1thg9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-AREfBoXwWnFtI4xGLtNzu4Moz_fixUk',
    appId: '1:733722860103:ios:46dda18fc8a002e4e32f62',
    messagingSenderId: '733722860103',
    projectId: 'shelfd-41c13',
    storageBucket: 'shelfd-41c13.firebasestorage.app',
    androidClientId: '733722860103-fj6plrhnufpdli34lm7qf1dgsdknvqc8.apps.googleusercontent.com',
    iosClientId: '733722860103-83htvqj5epf8vakv70rcq0bsek1thg9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

}